import { VideoRecommendationAdapter } from '@contentModule/core/adapter/video-recommendation.adapter.interface'
import { VideoSummaryAdapter } from '@contentModule/core/adapter/video-summary.adapter.interface'
import { VideoTranscriptAdapter } from '@contentModule/core/adapter/video-transcript.adapter.interface'
import { VideoMetadata } from '@contentModule/persistence/entity/video-metadata.entity'
import { Inject, Injectable } from '@nestjs/common'
import { Video } from '@src/module/content/persistence/entity/video.entity'

@Injectable()
export class VideoProcessorService {
  constructor(
    @Inject(VideoSummaryAdapter)
    private readonly videoSummaryGenerator: VideoSummaryAdapter,
    @Inject(VideoTranscriptAdapter)
    private readonly videoTranscriptGenerator: VideoTranscriptAdapter,
    @Inject(VideoRecommendationAdapter)
    private readonly videoAgeRecommendationAdapter: VideoRecommendationAdapter,
  ) {}

  async processMetadataAndModeration(video: Video) {
    const summary = await this.videoSummaryGenerator.generateSummary(video.url)
    const transcript = await this.videoTranscriptGenerator.generateTranscript(
      video.url,
    )
    const ageRecommendation =
      await this.videoAgeRecommendationAdapter.getAgeRecommendation(video.url)

    video.metadata = new VideoMetadata({
      autoGeneratedDescription: summary,
      transcript,
      ageRating: ageRecommendation?.ageRating,
      ageRatingExplanation: ageRecommendation?.explanation,
      ageRatingCategories: ageRecommendation?.categories,
    })
  }
}
