import { VideoMetadata } from '@contentModule/persistence/entity/video-metadata.entity'
import { Video } from '@contentModule/persistence/entity/video.entity'
import { VideoMetadataRepository } from '@contentModule/persistence/repository/video-metadata.repository'
import { Inject, Injectable } from '@nestjs/common'
import { AppLogger } from '@sharedModules/logger/service/app-logger.service'
import { VideoSummaryAdapter } from '../adapter/video-summary.adapter.interface'

@Injectable()
export class GenerateSummaryForVideoUseCase {
  constructor(
    @Inject(VideoSummaryAdapter)
    private readonly videoSummary: VideoSummaryAdapter,
    private readonly videoMetadataRepository: VideoMetadataRepository,
    private readonly logger: AppLogger,
  ) {}

  public async execute(video: Video): Promise<void> {
    const summary = await this.videoSummary.generateSummary(video.url)

    if (!summary) {
      throw new Error(
        `Failed to generate summary for video with ID ${video.id}`,
      )
    }

    this.logger.log(`Generated summary for video ID ${video.id}`, {
      summary,
      videoId: video.id,
    })

    const metadata = await this.videoMetadataRepository.findOneBy({
      where: { video },
    })

    if (metadata) {
      metadata.autoGeneratedDescription = summary
      await this.videoMetadataRepository.save(metadata)
      return
    }

    const newMetadata = new VideoMetadata({
      autoGeneratedDescription: summary,
      video,
    })

    await this.videoMetadataRepository.save(newMetadata)
  }
}
